/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarredRouteImport } from './routes/starred'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as DeletedRouteImport } from './routes/deleted'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ArchivedRouteImport } from './routes/archived'
import { Route as AllRouteImport } from './routes/all'
import { Route as TagTagIdRouteImport } from './routes/tag.$tagId'
import { Route as FavoriteFavoriteIdRouteImport } from './routes/favorite.$favoriteId'
import { Route as StarredArticleArticleIdRouteImport } from './routes/starred.article.$articleId'
import { Route as RecentArticleArticleIdRouteImport } from './routes/recent.article.$articleId'
import { Route as DeletedArticleArticleIdRouteImport } from './routes/deleted.article.$articleId'
import { Route as ArchivedArticleArticleIdRouteImport } from './routes/archived.article.$articleId'
import { Route as AllArticleArticleIdRouteImport } from './routes/all.article.$articleId'
import { Route as TagTagIdArticleArticleIdRouteImport } from './routes/tag.$tagId.article.$articleId'
import { Route as FavoriteFavoriteIdArticleArticleIdRouteImport } from './routes/favorite.$favoriteId.article.$articleId'

const StarredRoute = StarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DeletedRoute = DeletedRouteImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivedRoute = ArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => rootRouteImport,
} as any)
const AllRoute = AllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagIdRoute = TagTagIdRouteImport.update({
  id: '/tag/$tagId',
  path: '/tag/$tagId',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoriteFavoriteIdRoute = FavoriteFavoriteIdRouteImport.update({
  id: '/favorite/$favoriteId',
  path: '/favorite/$favoriteId',
  getParentRoute: () => rootRouteImport,
} as any)
const StarredArticleArticleIdRoute = StarredArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => StarredRoute,
} as any)
const RecentArticleArticleIdRoute = RecentArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => RecentRoute,
} as any)
const DeletedArticleArticleIdRoute = DeletedArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => DeletedRoute,
} as any)
const ArchivedArticleArticleIdRoute = ArchivedArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => ArchivedRoute,
} as any)
const AllArticleArticleIdRoute = AllArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => AllRoute,
} as any)
const TagTagIdArticleArticleIdRoute = TagTagIdArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => TagTagIdRoute,
} as any)
const FavoriteFavoriteIdArticleArticleIdRoute = FavoriteFavoriteIdArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => FavoriteFavoriteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/all': typeof AllRouteWithChildren
  '/archived': typeof ArchivedRouteWithChildren
  '/chat': typeof ChatRoute
  '/deleted': typeof DeletedRouteWithChildren
  '/graph': typeof GraphRoute
  '/recent': typeof RecentRouteWithChildren
  '/search': typeof SearchRoute
  '/starred': typeof StarredRouteWithChildren
  '/favorite/$favoriteId': typeof FavoriteFavoriteIdRouteWithChildren
  '/tag/$tagId': typeof TagTagIdRouteWithChildren
  '/all/article/$articleId': typeof AllArticleArticleIdRoute
  '/archived/article/$articleId': typeof ArchivedArticleArticleIdRoute
  '/deleted/article/$articleId': typeof DeletedArticleArticleIdRoute
  '/recent/article/$articleId': typeof RecentArticleArticleIdRoute
  '/starred/article/$articleId': typeof StarredArticleArticleIdRoute
  '/favorite/$favoriteId/article/$articleId': typeof FavoriteFavoriteIdArticleArticleIdRoute
  '/tag/$tagId/article/$articleId': typeof TagTagIdArticleArticleIdRoute
}
export interface FileRoutesByTo {
  '/all': typeof AllRouteWithChildren
  '/archived': typeof ArchivedRouteWithChildren
  '/chat': typeof ChatRoute
  '/deleted': typeof DeletedRouteWithChildren
  '/graph': typeof GraphRoute
  '/recent': typeof RecentRouteWithChildren
  '/search': typeof SearchRoute
  '/starred': typeof StarredRouteWithChildren
  '/favorite/$favoriteId': typeof FavoriteFavoriteIdRouteWithChildren
  '/tag/$tagId': typeof TagTagIdRouteWithChildren
  '/all/article/$articleId': typeof AllArticleArticleIdRoute
  '/archived/article/$articleId': typeof ArchivedArticleArticleIdRoute
  '/deleted/article/$articleId': typeof DeletedArticleArticleIdRoute
  '/recent/article/$articleId': typeof RecentArticleArticleIdRoute
  '/starred/article/$articleId': typeof StarredArticleArticleIdRoute
  '/favorite/$favoriteId/article/$articleId': typeof FavoriteFavoriteIdArticleArticleIdRoute
  '/tag/$tagId/article/$articleId': typeof TagTagIdArticleArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/all': typeof AllRouteWithChildren
  '/archived': typeof ArchivedRouteWithChildren
  '/chat': typeof ChatRoute
  '/deleted': typeof DeletedRouteWithChildren
  '/graph': typeof GraphRoute
  '/recent': typeof RecentRouteWithChildren
  '/search': typeof SearchRoute
  '/starred': typeof StarredRouteWithChildren
  '/favorite/$favoriteId': typeof FavoriteFavoriteIdRouteWithChildren
  '/tag/$tagId': typeof TagTagIdRouteWithChildren
  '/all/article/$articleId': typeof AllArticleArticleIdRoute
  '/archived/article/$articleId': typeof ArchivedArticleArticleIdRoute
  '/deleted/article/$articleId': typeof DeletedArticleArticleIdRoute
  '/recent/article/$articleId': typeof RecentArticleArticleIdRoute
  '/starred/article/$articleId': typeof StarredArticleArticleIdRoute
  '/favorite/$favoriteId/article/$articleId': typeof FavoriteFavoriteIdArticleArticleIdRoute
  '/tag/$tagId/article/$articleId': typeof TagTagIdArticleArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/all'
    | '/archived'
    | '/chat'
    | '/deleted'
    | '/graph'
    | '/recent'
    | '/search'
    | '/starred'
    | '/favorite/$favoriteId'
    | '/tag/$tagId'
    | '/all/article/$articleId'
    | '/archived/article/$articleId'
    | '/deleted/article/$articleId'
    | '/recent/article/$articleId'
    | '/starred/article/$articleId'
    | '/favorite/$favoriteId/article/$articleId'
    | '/tag/$tagId/article/$articleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/all'
    | '/archived'
    | '/chat'
    | '/deleted'
    | '/graph'
    | '/recent'
    | '/search'
    | '/starred'
    | '/favorite/$favoriteId'
    | '/tag/$tagId'
    | '/all/article/$articleId'
    | '/archived/article/$articleId'
    | '/deleted/article/$articleId'
    | '/recent/article/$articleId'
    | '/starred/article/$articleId'
    | '/favorite/$favoriteId/article/$articleId'
    | '/tag/$tagId/article/$articleId'
  id:
    | '__root__'
    | '/all'
    | '/archived'
    | '/chat'
    | '/deleted'
    | '/graph'
    | '/recent'
    | '/search'
    | '/starred'
    | '/favorite/$favoriteId'
    | '/tag/$tagId'
    | '/all/article/$articleId'
    | '/archived/article/$articleId'
    | '/deleted/article/$articleId'
    | '/recent/article/$articleId'
    | '/starred/article/$articleId'
    | '/favorite/$favoriteId/article/$articleId'
    | '/tag/$tagId/article/$articleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AllRoute: typeof AllRouteWithChildren
  ArchivedRoute: typeof ArchivedRouteWithChildren
  ChatRoute: typeof ChatRoute
  DeletedRoute: typeof DeletedRouteWithChildren
  GraphRoute: typeof GraphRoute
  RecentRoute: typeof RecentRouteWithChildren
  SearchRoute: typeof SearchRoute
  StarredRoute: typeof StarredRouteWithChildren
  FavoriteFavoriteIdRoute: typeof FavoriteFavoriteIdRouteWithChildren
  TagTagIdRoute: typeof TagTagIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/starred': {
      id: '/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof StarredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deleted': {
      id: '/deleted'
      path: '/deleted'
      fullPath: '/deleted'
      preLoaderRoute: typeof DeletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archived': {
      id: '/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof ArchivedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all': {
      id: '/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tagId': {
      id: '/tag/$tagId'
      path: '/tag/$tagId'
      fullPath: '/tag/$tagId'
      preLoaderRoute: typeof TagTagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite/$favoriteId': {
      id: '/favorite/$favoriteId'
      path: '/favorite/$favoriteId'
      fullPath: '/favorite/$favoriteId'
      preLoaderRoute: typeof FavoriteFavoriteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starred/article/$articleId': {
      id: '/starred/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/starred/article/$articleId'
      preLoaderRoute: typeof StarredArticleArticleIdRouteImport
      parentRoute: typeof StarredRoute
    }
    '/recent/article/$articleId': {
      id: '/recent/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/recent/article/$articleId'
      preLoaderRoute: typeof RecentArticleArticleIdRouteImport
      parentRoute: typeof RecentRoute
    }
    '/deleted/article/$articleId': {
      id: '/deleted/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/deleted/article/$articleId'
      preLoaderRoute: typeof DeletedArticleArticleIdRouteImport
      parentRoute: typeof DeletedRoute
    }
    '/archived/article/$articleId': {
      id: '/archived/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/archived/article/$articleId'
      preLoaderRoute: typeof ArchivedArticleArticleIdRouteImport
      parentRoute: typeof ArchivedRoute
    }
    '/all/article/$articleId': {
      id: '/all/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/all/article/$articleId'
      preLoaderRoute: typeof AllArticleArticleIdRouteImport
      parentRoute: typeof AllRoute
    }
    '/tag/$tagId/article/$articleId': {
      id: '/tag/$tagId/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/tag/$tagId/article/$articleId'
      preLoaderRoute: typeof TagTagIdArticleArticleIdRouteImport
      parentRoute: typeof TagTagIdRoute
    }
    '/favorite/$favoriteId/article/$articleId': {
      id: '/favorite/$favoriteId/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/favorite/$favoriteId/article/$articleId'
      preLoaderRoute: typeof FavoriteFavoriteIdArticleArticleIdRouteImport
      parentRoute: typeof FavoriteFavoriteIdRoute
    }
  }
}

interface AllRouteChildren {
  AllArticleArticleIdRoute: typeof AllArticleArticleIdRoute
}

const AllRouteChildren: AllRouteChildren = {
  AllArticleArticleIdRoute: AllArticleArticleIdRoute,
}

const AllRouteWithChildren = AllRoute._addFileChildren(AllRouteChildren)

interface ArchivedRouteChildren {
  ArchivedArticleArticleIdRoute: typeof ArchivedArticleArticleIdRoute
}

const ArchivedRouteChildren: ArchivedRouteChildren = {
  ArchivedArticleArticleIdRoute: ArchivedArticleArticleIdRoute,
}

const ArchivedRouteWithChildren = ArchivedRoute._addFileChildren(ArchivedRouteChildren)

interface DeletedRouteChildren {
  DeletedArticleArticleIdRoute: typeof DeletedArticleArticleIdRoute
}

const DeletedRouteChildren: DeletedRouteChildren = {
  DeletedArticleArticleIdRoute: DeletedArticleArticleIdRoute,
}

const DeletedRouteWithChildren = DeletedRoute._addFileChildren(DeletedRouteChildren)

interface RecentRouteChildren {
  RecentArticleArticleIdRoute: typeof RecentArticleArticleIdRoute
}

const RecentRouteChildren: RecentRouteChildren = {
  RecentArticleArticleIdRoute: RecentArticleArticleIdRoute,
}

const RecentRouteWithChildren = RecentRoute._addFileChildren(RecentRouteChildren)

interface StarredRouteChildren {
  StarredArticleArticleIdRoute: typeof StarredArticleArticleIdRoute
}

const StarredRouteChildren: StarredRouteChildren = {
  StarredArticleArticleIdRoute: StarredArticleArticleIdRoute,
}

const StarredRouteWithChildren = StarredRoute._addFileChildren(StarredRouteChildren)

interface FavoriteFavoriteIdRouteChildren {
  FavoriteFavoriteIdArticleArticleIdRoute: typeof FavoriteFavoriteIdArticleArticleIdRoute
}

const FavoriteFavoriteIdRouteChildren: FavoriteFavoriteIdRouteChildren = {
  FavoriteFavoriteIdArticleArticleIdRoute: FavoriteFavoriteIdArticleArticleIdRoute,
}

const FavoriteFavoriteIdRouteWithChildren = FavoriteFavoriteIdRoute._addFileChildren(FavoriteFavoriteIdRouteChildren)

interface TagTagIdRouteChildren {
  TagTagIdArticleArticleIdRoute: typeof TagTagIdArticleArticleIdRoute
}

const TagTagIdRouteChildren: TagTagIdRouteChildren = {
  TagTagIdArticleArticleIdRoute: TagTagIdArticleArticleIdRoute,
}

const TagTagIdRouteWithChildren = TagTagIdRoute._addFileChildren(TagTagIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AllRoute: AllRouteWithChildren,
  ArchivedRoute: ArchivedRouteWithChildren,
  ChatRoute: ChatRoute,
  DeletedRoute: DeletedRouteWithChildren,
  GraphRoute: GraphRoute,
  RecentRoute: RecentRouteWithChildren,
  SearchRoute: SearchRoute,
  StarredRoute: StarredRouteWithChildren,
  FavoriteFavoriteIdRoute: FavoriteFavoriteIdRouteWithChildren,
  TagTagIdRoute: TagTagIdRouteWithChildren,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
