/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarredRouteImport } from './routes/starred'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagTagIdRouteImport } from './routes/tag.$tagId'
import { Route as FavoriteFavoriteIdRouteImport } from './routes/favorite.$favoriteId'
import { Route as ArticleArticleIdRouteImport } from './routes/article.$articleId'
import { Route as StarredArticleArticleIdRouteImport } from './routes/starred.article.$articleId'
import { Route as RecentArticleArticleIdRouteImport } from './routes/recent.article.$articleId'
import { Route as TagTagIdArticleArticleIdRouteImport } from './routes/tag.$tagId.article.$articleId'
import { Route as FavoriteFavoriteIdArticleArticleIdRouteImport } from './routes/favorite.$favoriteId.article.$articleId'

const StarredRoute = StarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagIdRoute = TagTagIdRouteImport.update({
  id: '/tag/$tagId',
  path: '/tag/$tagId',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoriteFavoriteIdRoute = FavoriteFavoriteIdRouteImport.update({
  id: '/favorite/$favoriteId',
  path: '/favorite/$favoriteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleArticleIdRoute = ArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const StarredArticleArticleIdRoute = StarredArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => StarredRoute,
} as any)
const RecentArticleArticleIdRoute = RecentArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => RecentRoute,
} as any)
const TagTagIdArticleArticleIdRoute = TagTagIdArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => TagTagIdRoute,
} as any)
const FavoriteFavoriteIdArticleArticleIdRoute = FavoriteFavoriteIdArticleArticleIdRouteImport.update({
  id: '/article/$articleId',
  path: '/article/$articleId',
  getParentRoute: () => FavoriteFavoriteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/recent': typeof RecentRouteWithChildren
  '/search': typeof SearchRoute
  '/starred': typeof StarredRouteWithChildren
  '/article/$articleId': typeof ArticleArticleIdRoute
  '/favorite/$favoriteId': typeof FavoriteFavoriteIdRouteWithChildren
  '/tag/$tagId': typeof TagTagIdRouteWithChildren
  '/recent/article/$articleId': typeof RecentArticleArticleIdRoute
  '/starred/article/$articleId': typeof StarredArticleArticleIdRoute
  '/favorite/$favoriteId/article/$articleId': typeof FavoriteFavoriteIdArticleArticleIdRoute
  '/tag/$tagId/article/$articleId': typeof TagTagIdArticleArticleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/recent': typeof RecentRouteWithChildren
  '/search': typeof SearchRoute
  '/starred': typeof StarredRouteWithChildren
  '/article/$articleId': typeof ArticleArticleIdRoute
  '/favorite/$favoriteId': typeof FavoriteFavoriteIdRouteWithChildren
  '/tag/$tagId': typeof TagTagIdRouteWithChildren
  '/recent/article/$articleId': typeof RecentArticleArticleIdRoute
  '/starred/article/$articleId': typeof StarredArticleArticleIdRoute
  '/favorite/$favoriteId/article/$articleId': typeof FavoriteFavoriteIdArticleArticleIdRoute
  '/tag/$tagId/article/$articleId': typeof TagTagIdArticleArticleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graph': typeof GraphRoute
  '/recent': typeof RecentRouteWithChildren
  '/search': typeof SearchRoute
  '/starred': typeof StarredRouteWithChildren
  '/article/$articleId': typeof ArticleArticleIdRoute
  '/favorite/$favoriteId': typeof FavoriteFavoriteIdRouteWithChildren
  '/tag/$tagId': typeof TagTagIdRouteWithChildren
  '/recent/article/$articleId': typeof RecentArticleArticleIdRoute
  '/starred/article/$articleId': typeof StarredArticleArticleIdRoute
  '/favorite/$favoriteId/article/$articleId': typeof FavoriteFavoriteIdArticleArticleIdRoute
  '/tag/$tagId/article/$articleId': typeof TagTagIdArticleArticleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/graph'
    | '/recent'
    | '/search'
    | '/starred'
    | '/article/$articleId'
    | '/favorite/$favoriteId'
    | '/tag/$tagId'
    | '/recent/article/$articleId'
    | '/starred/article/$articleId'
    | '/favorite/$favoriteId/article/$articleId'
    | '/tag/$tagId/article/$articleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/graph'
    | '/recent'
    | '/search'
    | '/starred'
    | '/article/$articleId'
    | '/favorite/$favoriteId'
    | '/tag/$tagId'
    | '/recent/article/$articleId'
    | '/starred/article/$articleId'
    | '/favorite/$favoriteId/article/$articleId'
    | '/tag/$tagId/article/$articleId'
  id:
    | '__root__'
    | '/'
    | '/graph'
    | '/recent'
    | '/search'
    | '/starred'
    | '/article/$articleId'
    | '/favorite/$favoriteId'
    | '/tag/$tagId'
    | '/recent/article/$articleId'
    | '/starred/article/$articleId'
    | '/favorite/$favoriteId/article/$articleId'
    | '/tag/$tagId/article/$articleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphRoute: typeof GraphRoute
  RecentRoute: typeof RecentRouteWithChildren
  SearchRoute: typeof SearchRoute
  StarredRoute: typeof StarredRouteWithChildren
  ArticleArticleIdRoute: typeof ArticleArticleIdRoute
  FavoriteFavoriteIdRoute: typeof FavoriteFavoriteIdRouteWithChildren
  TagTagIdRoute: typeof TagTagIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/starred': {
      id: '/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof StarredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$tagId': {
      id: '/tag/$tagId'
      path: '/tag/$tagId'
      fullPath: '/tag/$tagId'
      preLoaderRoute: typeof TagTagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite/$favoriteId': {
      id: '/favorite/$favoriteId'
      path: '/favorite/$favoriteId'
      fullPath: '/favorite/$favoriteId'
      preLoaderRoute: typeof FavoriteFavoriteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$articleId': {
      id: '/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/article/$articleId'
      preLoaderRoute: typeof ArticleArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starred/article/$articleId': {
      id: '/starred/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/starred/article/$articleId'
      preLoaderRoute: typeof StarredArticleArticleIdRouteImport
      parentRoute: typeof StarredRoute
    }
    '/recent/article/$articleId': {
      id: '/recent/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/recent/article/$articleId'
      preLoaderRoute: typeof RecentArticleArticleIdRouteImport
      parentRoute: typeof RecentRoute
    }
    '/tag/$tagId/article/$articleId': {
      id: '/tag/$tagId/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/tag/$tagId/article/$articleId'
      preLoaderRoute: typeof TagTagIdArticleArticleIdRouteImport
      parentRoute: typeof TagTagIdRoute
    }
    '/favorite/$favoriteId/article/$articleId': {
      id: '/favorite/$favoriteId/article/$articleId'
      path: '/article/$articleId'
      fullPath: '/favorite/$favoriteId/article/$articleId'
      preLoaderRoute: typeof FavoriteFavoriteIdArticleArticleIdRouteImport
      parentRoute: typeof FavoriteFavoriteIdRoute
    }
  }
}

interface RecentRouteChildren {
  RecentArticleArticleIdRoute: typeof RecentArticleArticleIdRoute
}

const RecentRouteChildren: RecentRouteChildren = {
  RecentArticleArticleIdRoute: RecentArticleArticleIdRoute,
}

const RecentRouteWithChildren = RecentRoute._addFileChildren(RecentRouteChildren)

interface StarredRouteChildren {
  StarredArticleArticleIdRoute: typeof StarredArticleArticleIdRoute
}

const StarredRouteChildren: StarredRouteChildren = {
  StarredArticleArticleIdRoute: StarredArticleArticleIdRoute,
}

const StarredRouteWithChildren = StarredRoute._addFileChildren(StarredRouteChildren)

interface FavoriteFavoriteIdRouteChildren {
  FavoriteFavoriteIdArticleArticleIdRoute: typeof FavoriteFavoriteIdArticleArticleIdRoute
}

const FavoriteFavoriteIdRouteChildren: FavoriteFavoriteIdRouteChildren = {
  FavoriteFavoriteIdArticleArticleIdRoute: FavoriteFavoriteIdArticleArticleIdRoute,
}

const FavoriteFavoriteIdRouteWithChildren = FavoriteFavoriteIdRoute._addFileChildren(FavoriteFavoriteIdRouteChildren)

interface TagTagIdRouteChildren {
  TagTagIdArticleArticleIdRoute: typeof TagTagIdArticleArticleIdRoute
}

const TagTagIdRouteChildren: TagTagIdRouteChildren = {
  TagTagIdArticleArticleIdRoute: TagTagIdArticleArticleIdRoute,
}

const TagTagIdRouteWithChildren = TagTagIdRoute._addFileChildren(TagTagIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphRoute: GraphRoute,
  RecentRoute: RecentRouteWithChildren,
  SearchRoute: SearchRoute,
  StarredRoute: StarredRouteWithChildren,
  ArticleArticleIdRoute: ArticleArticleIdRoute,
  FavoriteFavoriteIdRoute: FavoriteFavoriteIdRouteWithChildren,
  TagTagIdRoute: TagTagIdRouteWithChildren,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
